### PR TITLE
remove gistic, add annotSV

### PR DESCRIPTION
**Pull request by jharenza**
- Remove GISTIC since we have it within OpenPBTA
- Add AnnotSV since it was in its own repo: https://github.com/d3b-center/annotSV

@migbro should we keep _all_ DockerFile, CWL and wf.CWL? I set it up as a folder since there were three files to go with the tool, even though none of the others have this many files. Just didn't want to lose anything.

### CODE REVIEW

**Comment by jharenza** [comment]
Cc @zhangb1 about AnnotSV here - do you have an official KF CWL or should we use @kgaonkar6's code

**Comment by zhangb1** [comment]
I don't have the CWL. when I ran the tool in cavatica, I used the one from Krutika. 
https://cavatica.sbgenomics.com/u/gaonkark/cbttc-dev/apps/#gaonkark/cbttc-dev/annotsv/7

**Comment by jharenza** [comment]
@migbro can you review this now please?

**Review by migbro — APPROVED** [review]
Looks good!

**Pull request merged**
